### ISSUE TITLE
Action parameters not working correctly 

### ISSUE THREAD

**Issue by ge022** [bitfocus/companion-module-chamsys-quickq#4]
'quickq: Control 10Scene button' in companion 
Not setting Zone (optional), doesn't toggle activation. 
When "Zone (optional)" is set to "1", the cue activates, and when set to "0", it deactivates. The "Activate" checkbox does nothing.

 I'm looking at the Remote Log in the chamsys console, when zone is empty or set to "0", I see "OSC: /10scene/3 i 0" (3 is the cue). This deactivates the cue but doesn't toggle it. Activate checkbox doesn't change url.
When zone set to 1, I see: "OSC: /10scene/3/1 i 1". This activates the cue.

**Comment by goddard244** [comment]
I put a fix in for this but don't know when it will be put in a release.

**Comment by bryce-seifert** [comment]
Fixed with https://github.com/bitfocus/companion-module-chamsys-quickq/pull/11
